### ISSUE TITLE
Node version inconsistency

### ISSUE THREAD

**Issue by domoritz** [yuzutech/kroki#112]
https://github.com/yuzutech/kroki/blob/0ff2cbe0fa9c5c68c3bba76b34ae6cd36b76eb1d/vega/ops/docker/alpine/Dockerfile#L17

I noticed that the docker image is node 12 but the line above says node 10. Should it be node 12?

**Comment by Mogztter** [comment]
Not necessarily, we are using Node 12 to build a static binary with [pkg](https://github.com/zeit/pkg). As far as I know, there's no difference between using Node 10 to build a static binary or Node 12.

Initially, my plan was to upgrade both the Docker image and the target to the latest LTS (Node 12.16.1) but `pkg-fetch` is outdated: https://github.com/zeit/pkg-fetch/issues/79
So I decided to stay on node10 until this issue is fixed.

**Comment by domoritz** [comment]
I have seen version incompatibilities with binaries but I'm glad to hear that node 10 and 12 works for you. Anyway, feel free to close this issue or keep it open until https://github.com/zeit/pkg-fetch/issues/79 is fixed and you can update.

**Comment by Mogztter** [comment]
I will keep it open as a reminder, thanks 😉

**Comment by Mogztter** [comment]
We are now using Node 14 across the board.
