### ISSUE TITLE
Update openjdk version from Dockerfile

### ISSUE THREAD

**Issue by zkorhone** [yuzutech/kroki#1137]
Seems like dependabot isn't managing ops/docker/jdk11-alpine/Dockerfile correctly. Version that server build is using as source is relatively old.

Any chance for an update? Our security scanner flags this as an issue.

**Comment by Mogztter** [comment]
Hey!

As mentioned in the Dockerfile, I didn't upgrade to a newer version but there was a SegFault:

https://github.com/yuzutech/kroki/blob/007c04de54a9fef82c0442d1ed75a7ad9ae60060/server/ops/docker/jdk11-alpine/Dockerfile#L2-L4

Having said that, it seems that this issue is now resolved so we are clear to upgrade.


> Seems like dependabot isn't managing ops/docker/jdk11-alpine/Dockerfile correctly

Dependabot is correctly configured and `adoptopenjdk/openjdk11 jre-11.0.9.1_1-alpine` is the latest version available.

https://github.com/yuzutech/kroki/blob/007c04de54a9fef82c0442d1ed75a7ad9ae60060/.github/dependabot.yml#L12-L17

```
updater | INFO <job_292704519> Starting update job for yuzutech/kroki
updater | INFO <job_292704519> Checking if adoptopenjdk/openjdk11 jre-11.0.9.1_1-alpine needs updating
updater | INFO <job_292704519> Latest version is jre-11.0.9.1_1-alpine
updater | INFO <job_292704519> No update needed for adoptopenjdk/openjdk11 jre-11.0.9.1_1-alpine
```

The reason is that `adoptopenjdk` is now an Eclipse project and newer images are published using a new name: `eclipse-temurin`

So we need to switch to: https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/11.0.14_9-jre-alpine/images/sha256-2d9fe6caa720dc96202fca6f65e0d00d2db7a58bd4cc34251c52b9172b467b79?context=explore

**Comment by skorhone** [comment]
Ahh, I missed that it was built from adoptopenjdk and not from openjdk 🙂
