### ISSUE TITLE
Nodes of mermaid are too narrow to display Japanese characters

### ISSUE THREAD

**Issue by m-miyawaki** [yuzutech/kroki#1167]
Hello,

When I use Mermaid in https://kroki.io,
width of nodes is too short to display full text written in Japanese.

Here is the source:

```
graph TD
  A[ あああああ ] -->|いいいい | B( ううううううう )

```

and the result:

https://kroki.io/mermaid/svg/eNpLL0osyFAIceFSUHCMVnjc2ISMFGIVdHXtah43tsCRQo2CkwZQXRsmUtAEGsIFAO2AJek=

Using mermaid.live, they are displayed correctly.

https://mermaid.live/view/#pako:eNqrVkrOT0lVslJKL0osyFAIcYnJU1BwjFZ43NiEjBRiFXR17WoeN7bAkUKNgpMGUF0bJlLQBJmipKOUm1qUm5iZAjS-GiQSo1SSkZqbGqNkBWSmpKYlluaUxCjF5NUClZYWpCSWpLqmZJbkFylZlRSVpuooJZaW5AdX5iXD-BA1LpmJQMfmQgRrAaFdTU0

**Comment by Mogztter** [comment]
I think the reason is that the Mermaid container does not include a CJK font. 
When using a PNG export, we can see that the characters are not display correctly: https://kroki.io/mermaid/png/eNpLL0osyFAIceFSUHCMVnjc2ISMFGIVdHXtah43tsCRQo2CkwZQXRsmUtAEAFZaJZU=

Similar to what we've done for #579, we should install `font-noto-cjk` in https://github.com/yuzutech/kroki/blob/26cd438c0646840f98c52b7aa9cd906331316af8/mermaid/Dockerfile#L34
