### ISSUE TITLE
Evaluate D2 from Terrastruct

### ISSUE THREAD

**Issue by Mogztter** [yuzutech/kroki#1323]
> It's currently in alpha, during which it's only housed on Terrastruct, which provides the most well-supported interface (IDE) for it. Once we have a stable v1, we'll release and continue development of it in open source and make local options available.

https://d2-lang.com/tour/intro

It looks interesting! 🧐

**Comment by alixander** [comment]
it is now open-source =)

https://github.com/terrastruct/d2

**Comment by Mogztter** [comment]
Looking good, thanks for the heads-up. I will prototype an integration 😄

**Comment by alixander** [comment]
@Mogztter , i found your PR there on v8go and had actually linked it in an issue of D2, sharing with a fellow maintainer that "oh cool, someone's working on this" https://github.com/terrastruct/d2/issues/31 

I didn't know til checking back here that it was motivated from this hah. I'm sure it's going to be useful for a lot of projects, but for D2, we've actually just moved off of v8go. It didn't support Windows, so that was a hard blocker. (running Javascript in Goja now).

The new release this morning has no dependency on v8go, hopefully that can remove this blocker!

**Comment by Mogztter** [comment]
Awesome! I will give it a try, thanks for the heads-up 🙌

**Comment by Mogztter** [comment]
Sneak peek:

![d2-kroki](https://user-images.githubusercontent.com/333276/206557100-578ed47b-13e5-41d9-98f6-22ee146ac759.gif)

**Comment by alixander** [comment]
unrelated to inclusion of D2 -- ty for the work you do in open source @Mogztter. When we were just starting on the design of D2 and researching various tools, Kroki made it easy to try out many. It's also clear how much value the community gets from Kroki -- I see it everywhere in threads on diagramming, including posts we make (https://news.ycombinator.com/item?id=33705778). Terrastruct is proud to sponsor your work.

**Comment by Mogztter** [comment]
Thank you so much, it means a lot 🤗

**Comment by Airkro** [comment]
How to passing D2 flags like: https://d2lang.com/tour/sketch

**Comment by ggrossetie** [comment]
@Airkro you can configure the theme:  https://docs.kroki.io/kroki/setup/diagram-options/#_d2 but the `sketch` option is not available. Please open a new issue to request this enhancement and feel free to submit pull request! 🤗
