### ISSUE TITLE
404s when running locally

### ISSUE THREAD

**Issue by shanemcd** [yuzutech/kroki#1324]
Hello. I'm trying to run Kroki locally. I've tried with both docker-compose, podman-compose, and Kubernetes without any luck.

When I visit localhost:8000, I see the main page:

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/773186/187786069-48d34e25-0e7b-41f6-a588-fa7911747f7a.png">

But when I try to navigate to any of the routes listed here, I get:

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/773186/187786284-9b5f147b-897b-40e4-b3f0-156c5a6470db.png">

I'm following the steps in the documentation for both docker/podman and Kubernetes:

- https://docs.kroki.io/kroki/setup/use-docker-or-podman/#_run_multiple_kroki_containers_together
- https://docs.kroki.io/kroki/setup/use-kubernetes/

Would appreciate any help. Thanks in advance.

**Comment by Mogztter** [comment]
I believe your installation is working but `/excalidraw` is not a valid endpoint. Arguably, we could return information about Excalidraw instead of a 404 but Kroki  API is design to create diagrams (images) from textual definitions.

Anyway, you should use `GET /{diagramName}/{outputFormat}/{diagramDefinitionEncoded}`, see: https://docs.kroki.io/kroki/setup/usage/

Also, Excalidraw is provided by a companion container, so make sure that the `yuzutech/kroki-excalidraw` container is running: https://docs.kroki.io/kroki/setup/install/#_companion_containers

In the future, please direct usage questions to the project chat at https://kroki.zulipchat.com/. The issue tracker is for reporting bugs and feature proposals. Thanks!
