### ISSUE TITLE
Respect `PLANTUML_LIMIT_SIZE` for png images

### ISSUE THREAD

**Issue by nejch** [yuzutech/kroki#1339]
Context: https://plantuml.com/faq#e689668a91b8d065

> PlantUML limits image width and height to 4096. There is an environment variable that you can set to override this limit: `PLANTUML_LIMIT_SIZE`. You have to define this variable before launching PlantUML, something like:
>
> `set PLANTUML_LIMIT_SIZE=8192`

Unless I missed some other way of doing this it seems like this is ignored. I think over 4096 is excessive anyway but might be good to support this :) Works fine with svg though.

**Comment by Mogztter** [comment]
Did you try to set the environment variable with the `--env` option on `docker run`?
Since PlantUML is using [`System.getenv`](https://github.com/plantuml/plantuml/blob/62e5a00c8da63ad8d32c9a6d8a1cf49908cc32bc/src/net/sourceforge/plantuml/security/SecurityUtils.java#L196) to [get the environment variable](https://github.com/plantuml/plantuml/blob/62e5a00c8da63ad8d32c9a6d8a1cf49908cc32bc/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils.java#L156), I don't see why it should not work.

**Comment by nejch** [comment]
You're right @Mogztter, sorry for the noise. I did use `-e` but I must have messed up something there when trying last time. Just tried again and it worked. :)

**Comment by Mogztter** [comment]
> I did use -e but I must have messed up something there when trying last time. Just tried again and it worked. :)

Order matters, you might have specify the `-e` option after the image name... anyway, it also happens to me, no worries 😉
