### ISSUE TITLE
Update PlantUML to pick up memory leak fix

### ISSUE THREAD

**Issue by boris-moduscreate** [yuzutech/kroki#1358]
PlantUML have fixed a memory leak issue at https://github.com/plantuml/plantuml/issues/862
It would be great if Kroki could update to the version that isn't impacted

**Comment by Mogztter** [comment]
Thanks for the heads up.
Dependencies are automatically updated and there's already a pull request: https://github.com/yuzutech/kroki/pull/1351
The build is failing because we need to update a few assertions.

**Comment by khanguyen88** [comment]
@Mogztter 
Do you have an ETA on when this fix will be on Docker Hub?

**Comment by boris-moduscreate** [comment]
@Mogztter I guess our question is more "What is the trigger in this repo for a formal release to happen which would encapsulate this change and also push said version to Docker Hub?"

**Comment by Mogztter** [comment]
I would like to complete this pull request: https://github.com/yuzutech/kroki/pull/1360 (basically, replace `docker build` by `docker buildx`).

Then, we should update diagram library versions in a few places (I might automate this process one day). The reason is that Renovate only bump the version in the package.json or pom.xml but we do have a few references to diagram versions in the documentation and in the server.

Next step is to draft a release note and an announcement tweet.

Apart from that the release process is automated and triggered when a tag is pushed.

I usually do some local testing before releasing to make sure that's everything is working as expected but we should probably add a few integration tests.
