### ISSUE TITLE
PNG rendering has limited height (c4uml)

### ISSUE THREAD

**Issue by sasf54** [yuzutech/kroki#1385]
When rendering a tall diagram in C4UML + png, it cuts off the bottom.
Rendering to svg is fine.
rendering PNG will cut off some elements (about 8-9 in the attached example)
(about 35 component height, rendered ~ 32)

I attached an adoc, to reproduce the bug.

[kroki_bug.txt](https://github.com/yuzutech/kroki/files/10002630/kroki_bug.txt)
(about 9 elements left out)

Versions tested:
yuzutech/kroki:latest (~2022/11/10)
yuzutech/kroki:latest (2022/11/14)
yuzutech/kroki:0.18.0 (2022/11/14)
  plantuml | 1.2022.12

(The bug seems to be somewhere in the svg -> png conversion)

**Comment by Mogztter** [comment]
I get the same result using https://www.plantuml.com

https://www.plantuml.com/plantuml/png/SYWkIImgAStDuLBCp4lEAKr9LR1nDj5tDebtpiyhIQqeiSCgaPYPbrg4JIgt83ylDG-eoySnqZyq9Dx7rIqaFiZJtID4GvEBIm48u6eq4kCD37JK4nKC3DHr5DHTSr9pWQBgEkeAkWhgcfXg0OpNCOhNGGn7yTvJRAVbBydC97CDR-0VjX0M1V7-2A-KBLwJwjEzuai26yecDfKjR2cxi4lPZTtA7knHjh6jx617sOkznWRTub4siA5iObFPmfQo2xkKtTYjxC4UPHlRoWvsbBtOQspIBHzb0nlA9ZQLBMmfkx1BsOtToXxiKRQnhUnWHzcBlSOMtUfHDh2XR69JsSAMiWkxbDtOhUp17cKRsyeETfIzsFkP_VAVVh5mBx5msC26iebDPGjRoYxiKdPZjx87UvHjR2ixs57sOg-nGRTub0riA9lOLBQmfUp2BcKtTYjxi4VPnhQoWnrbB_OQctJBHzd0XhA9JMKBMyekx59sOxUo1tkKRMmhEzXHzcAliKMtUfGDR2YRs5IsiANimYvbDtOhUx17sSQsieCTPI_syuNx_lxnxOtFxUt5_Vhd_UF7tv-_V_rhWuvnAefX00XUwTbEOgVZCD017VS7hKJpjVLqywV_660u9fYE1PRZ0fVZ1hVZ0OzZW-quu3XUy2e6G_4u1XYE2QPZWUMumEMumUrumEFOO3iEE8uNzA5aA1_70CCnmNGii1mNk1mtk1qFU1mRRCS1n_62FbGCrUCOO3Wcc8u5bkC2b-C6j-C1ZsE3xJZWE5xmPUZju_lzv-lp5m00

The reason is:

> PlantUML limits image width and height to 4096. There is an environment variable that you can set to override this limit: PLANTUML_LIMIT_SIZE. You have to define this variable before launching PlantUML.

https://plantuml.com/en/faq

You should pass this environnement variable to the Kroki container:

```console
$ docker run -ePLANTUML_LIMIT_SIZE=8192 yuzutech/kroki
```

**Comment by sasf54** [comment]
\o/ solved it
(Did not found in Environment variables / hub.docker.com description)
THX
