### ISSUE TITLE
no pikchr diagram with adoc

### ISSUE THREAD

**Issue by lidaling** [yuzutech/kroki#1461]
when adoc with diagram block
```
[pikchr]
arrow
box "foo"
down
arrow
box "bar"
```
it shows:
java.io.IOException: Cannot run program "pikchr": error=2, No such file or directory

**Comment by ggrossetie** [comment]
I believe you are using Asciidoctor Diagram (or even Asciidoctor Diagram through Java/AsciidoctorJ).

Anyway, the extension you are using is trying to execute the `pikchr` program on your local machine.
This issue is not related to Kroki, please open a issue at https://github.com/asciidoctor/asciidoctor-diagram (if you are indeed using Asciidoctor Diagram).

You can also ask for help at https://chat.asciidoctor.org
