### ISSUE TITLE
Diagram option 'size' does not take effect

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1464]
As documented [here](https://docs.kroki.io/kroki/setup/diagram-options/#_blockdiag), you can adjust the size of your `blockdiag` diagrams using the `size` diagram option. This doesn't work for me, however:

```
$ http https://kroki.io/ diagram_type='actdiag' output_format='png' diagram_source='{lane Sysadmin}' diagram_options:='{"size": "128x100"  }' > diagram.png
```

This writes `diagram.png` on my disk. Regardless of any `size`setting, the generated `png` has always dimensions `256x200`:

```
$ file diagram.png
diagram.png: PNG image data, 256 x 200, 8-bit/color RGBA, non-interlaced
```

Same for output format `svg`:

```
$ http https://kroki.io/ diagram_type='actdiag' output_format='svg' diagram_source='{lane Sysadmin}' diagram_options:='{"size": "128x100"  }' > diagram.png
```
Generated `svg` has dimensions `256x200`, regardless of `size` settings:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkspace="http://www.inkscape.org/namespaces/inkscape" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 256 200" width="256px" height="200px">
```

**Comment by ggrossetie** [comment]
I don't think the size option will affect the size of a scalable image but it should affect the PNG image. As far as I can tell, we pass the value to the command line:

https://github.com/yuzutech/kroki/blob/a2e21f15c8ae6c8cec4ea0653624f49f9e51063c/blockdiag/src/backend/diag.py#L49-L51

Maybe we should use `--size 128x100` instead of `--size=128x100`... 🤔 
Some CLI does not adhere to the unix convention (i.e., `-s value` and `--long=value`)

**Comment by FelixVanOost** [comment]
> I don't think the size option will affect the size of a scalable image but it should affect the PNG image. As far as I can tell, we pass the value to the command line:
> 
> https://github.com/yuzutech/kroki/blob/a2e21f15c8ae6c8cec4ea0653624f49f9e51063c/blockdiag/src/backend/diag.py#L49-L51
> 
> Maybe we should use `--size 128x100` instead of `--size=128x100`... 🤔 Some CLI does not adhere to the unix convention (i.e., `-s value` and `--long=value`)

This seems to be correct based on the corresponding [test](https://github.com/blockdiag/blockdiag/blob/ce37f0c18dc7f88caab3d3b24aac4f3f066b793c/src/blockdiag/tests/test_boot_params.py#L162) in the blockdiag source code. All the arguments are separated by spaces.

**Comment by FelixVanOost** [comment]
After some more debugging, I suspect this might be an upstream issue with `blockdiag`. It looks like Kroki is formatting the `size` argument correctly, because passing an invalid size returns the following:

```
http https://kroki.io/ diagram_type='actdiag' output_format='png' diagram_source='{lane Sysadmin}' diagram_options:='{"size": "12345"}' > diagram.png
```

```
{"error":{"code":400,"message":"--size option must be formatted as WIDTHxHEIGHT."}}
```

Which indicates that `blockdiag` was able to parse the argument (see [here](https://github.com/blockdiag/blockdiag/blob/ce37f0c18dc7f88caab3d3b24aac4f3f066b793c/src/blockdiag/utils/bootstrap.py#LL192C73-L192C73)).

For completeness, I also tried passing `--size <SIZE>` instead of `--size=<SIZE>` but this returned an HTTP 500 error.

**Comment by ggrossetie** [comment]
Fixed in https://github.com/yuzutech/kroki/commit/c03064d295452cfd9f73ca0ebe8a5a01fea7ab55
