### ISSUE TITLE
Retrieving Mermaid diagrams from kroki.io: timeout

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1590]
Try to retrieving a mermaid diagram from kroki.io (e.g. from [here](https://kroki.io/#try)).

**Result**: Gateway time-out (Error code 504)

**Comment by ggrossetie** [comment]
Mermaid container probably crashed. I will investigate... We might want to create a new Chrome instance since I don't think that long running Chrome instances (via Puppeteer)  are very stable.

My guess is that eventually the Chrome instance runs out of ressources (memory leak, page not correctly closed, long JavaScript process, etc...).

**Comment by ggrossetie** [comment]
Actually, it's not Mermaid, the core container ran out of memory:

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "globalEventExecutor-1-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elastic-apm-sampling-profiler"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elastic-apm-sampling-profiler"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "vert.x-eventloop-thread-2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "vert.x-eventloop-thread-1"
```
