### ISSUE TITLE
Retrieving Mermaid diagrams from kroki.io: timeout

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1599]
The error mentioned in #1590 occurred again :cry:

Try to retrieving a mermaid diagram from kroki.io (e.g. from [here](https://kroki.io/#try)).

**Result**: Gateway time-out (Error code 504)

**Comment by ggrossetie** [comment]
I think this is a different issue since other endpoints seem unaffected.

I'm currently on vacation, so I won't be able to fix it until next week or so.

As a workaround, you can install Kroki on your own infrastructure.

In the future, and if there is enough demand, we could consider implementing a paid service with a Service Level Agreement (SLA) and guarantees on service availability. We might even provide dedicated instances per client.

Out of curiosity, is this something that you or your company would be interested in?
