### ISSUE TITLE
Use relative path for root page

### ISSUE THREAD

**Issue by nigjo** [yuzutech/kroki#16]
We are using Kroki behind a ReverseProxy and in an (virtual) subfolder. Everything is working fine, but the root page is not displayed properly because all resources are absolute paths.

**Comment by Mogztter** [comment]
Hello @nigjo 
That's a good point :+1: 

I think it should be enough to use relative paths (using a `.` suffix) in [hello.html](https://github.com/yuzutech/kroki/blob/master/server/src/main/resources/web/hello.html) and [error.html](https://github.com/yuzutech/kroki/blob/master/server/src/main/resources/web/error.html) 

For instance:

```html
<link rel="stylesheet" href="/css/main.css">
```

```html
<link rel="stylesheet" href="./css/main.css">
```

Could you please confirm that, if you manually update the href (using the DevTools on your browser), then the stylesheet is loaded?

**Comment by nigjo** [comment]
Yes. This will help.

**Comment by Mogztter** [comment]
Could you please share your reverse proxy configuration? You can replace/remove any sensitive information, I just want to reproduce this issue on a local environment to make sure that everything works as expected.

Thanks!

**Comment by nigjo** [comment]
I'm running Apache 2.4.x on Windows and Kroki on the same maschine on port 8082.

The relevant part for Kroki is this:
```
<Location /tools/kroki>
  ProxyPass         http://localhost:8082/ nocanon
  ProxyPassReverse  http://localhost:8082/
</Location>
```
I don't know if `nocanon` is really needed in this place. I didn't test that.

**Comment by Mogztter** [comment]
Thanks!
Actually it's more complicated than I had anticipated :sweat_smile: 

For the [hello.html](https://github.com/yuzutech/kroki/blob/master/server/src/main/resources/web/hello.html) page, the relative path is always `/` so using `./` should solve this issue.
But things are more complicated for the [error.html](https://github.com/yuzutech/kroki/blob/master/server/src/main/resources/web/error.html) page. The reason is that this page can be seen on a multitude of paths:

- `/kroki/plantuml/svg` -> `../assets/logo.svg`
- `/kroki/plantuml/svg/` -> `../../assets/logo.svg`
- `/kroki/plantuml/svg/abc` -> `../../assets/logo.svg`
- `/kroki/plantuml//svg/abc` -> `../../../assets/logo.svg`

The last one is tricky because the path is normalized!
I'm not sure when the path is normalized but the path on the Vert.x request is `plantuml/svg/abc` (not `/plantuml//svg/abc`).

I also want to avoid to add a new configuration.

Since the HTML pages are really simple, I think the best solution is to embed the stylesheet and the SVG logo in the HTML.

**Comment by Mogztter** [comment]
@nigjo I will release a new version tomorrow or early next week. Are you using the Docker images or the jar file?

**Comment by nigjo** [comment]
We are using the jar file. It matches our setup more since we are not using docker on our windows server.

**Comment by Mogztter** [comment]
Awesome, I've published a pre-release: https://github.com/yuzutech/kroki/releases/tag/v0.0.8 (with the jar attached).

I will soon publish a new version on https://hub.docker.com/
