### ISSUE TITLE
how to add latex support in plantuml when using docker

### ISSUE THREAD

**Issue by jdysya** [yuzutech/kroki#1623]
As refered in #442 , the current kroki core did not support the latex in plantuml. Now, I am using the docker to render the diagram, as [the plantuml official website](https://plantuml.com/ascii-math), we just need download the [JLatexMath](https://github.com/opencollab/jlatexmath) and unzip it in the same directory with the `plantuml.jar`, however when I found the library in the `/usr/bin/plantuml`, I found it was not a `jar` file, but a Binary file，so what should to do next？
![image](https://github.com/yuzutech/kroki/assets/73117213/04c31514-8ec0-472c-a75b-fd04a2f0a12a)

**Comment by ggrossetie** [comment]
We've switched to a native image (generated by GraalVM) and it's no longer possible to use this workaround (i.e., copy the jlatexmath.jar in the Docker container). As far as I know ,the JLatexMath jar must be included before generating the native image.

If we dedice that we want to support this feature natively, then we will need to add the JLatexMath as part of the native image generation: https://github.com/yuzutech/plantuml/blob/master/.github/workflows/native-image-on-demand.yml

Since there's already an issue open for supporting JLatexMath, I'm closing this one.

If you have additional questions, please use the community chat: https://kroki.zulipchat.com/

**Comment by jdysya** [comment]
> If we dedice that we want to support this feature natively, then we will need to add the JLatexMath as part of the native image generation: https://github.com/yuzutech/plantuml/blob/master/.github/workflows/native-image-on-demand.yml

So, where have the out-of-the-box Binary file including the JLatexMath?
Since I am not familiar with it, I have taken annother measure: I delete the the original binary file in the `/usr/bin/plantuml`, and add a shell script with the same filename:
```shell
#!/bin/bash
   java -jar /usr/local/bin/plantuml/plantuml.jar "$@"
```
then we just need to put the releted `jar` file:
<img width="826" alt="image" src="https://github.com/yuzutech/kroki/assets/73117213/c7529854-5545-4655-8bb3-014c01d1043b">

We just need  regenerate another image, and then it come into effect. 

The above just is my methods, I don't think it is a good idea. I just want more people having the same trouble know.

**Comment by ggrossetie** [comment]
That's actually a good workaround! Thanks for sharing 👍

**Comment by ggrossetie** [comment]
> So, where have the out-of-the-box Binary file including the JLatexMath? The release may not mention it

For now it does not exist.
