### ISSUE TITLE
unable to produce plantuml C4 diagram

### ISSUE THREAD

**Issue by danieleades** [yuzutech/kroki#1673]
having issues generating a plantuml diagram.

> WARNING: kroki plantuml diagram (svg) with source '@startuml\n!include <C4/C4_Container>\n\nPerson(personAlias, "Label", "Optional Description")\nContainer(containerAlias, "Label", "Technology", "Optional Description")\nSystem(systemAlias, "Label", "Optional Description")\n\nRel(personAlias, containerAlias, "Label", "Optional Technology")\n@enduml\n': kroki did not produce a diagram
> 
> Exception occurred:
>   File "/workspace/.cache/virtualenvs/sb-bcps-xS3fZVNL-py3.12/lib/python3.12/site-packages/sphinxcontrib/kroki/transform.py", line 60, in render
>     raise SkipNode from exc
> docutils.nodes.SkipNode
> 

the diagram itself is included by path like so

```rst
.. kroki:: path/to/diagram.puml
    :name: some name
    :caption: some caption
```

any ideas?

**Comment by ggrossetie** [comment]
This is not the right repository, it seems related to `/sphinxcontrib/kroki/transform.py`. You will have to provide the log from the Kroki server otherwise I cannot help.

Please join https://kroki.zulipchat.com/. The issue tracker is reserved for bug reports and formal proposals for an enhancement.
