### ISSUE TITLE
Japanese text result is incorrect for png format

### ISSUE THREAD

**Issue by kaala** [yuzutech/kroki#386]
original diagram

```
digraph D {
   b1 [label = "第一次川中島の戦い\n1553年"];
   b2 [label = "第二次川中島の戦い\n1555年"];
   b4 [label = "第三次川中島の戦い\n1557年"];
   b1 -> b2 -> b4;
}
```

compare PNG and SVG

https://kroki.io/graphviz/svg/eNpLyUwvSizIUHBRqOZSUFBIMlSIzklMSs1RsFVQer5mzZMdDc_WLHy6fe6THWufbt72uHHds45ljxtbYvIMTU2Nn-7cohRrDdZnhKZvVw9ufaZI-kzQ7evErc8cSZ-hgq4dyFYQaWLNVQsALpNctA==

https://kroki.io/graphviz/png/eNpLyUwvSizIUHBRqOZSUFBIMlSIzklMSs1RsFVQer5mzZMdDc_WLHy6fe6THWufbt72uHHds45ljxtbYvIMTU2Nn-7cohRrDdZnhKZvVw9ufaZI-kzQ7evErc8cSZ-hgq4dyFYQaWLNVQsALpNctA==

**Comment by Mogztter** [comment]
Thanks for your report @kaala 👍 
I can reproduce this issue, I will investigate!

**Comment by Mogztter** [comment]
@kaala Apparently, it was fixed in https://github.com/yuzutech/kroki/commit/bd124e0f14606fd96058565fed2d1a6571b88070

Could you please confirm that Japanese texts now render properly? Not sure if [wqy-zenhei](https://packages.debian.org/fr/sid/fonts-wqy-zenhei) is good enough or if we should use Noto CJK instead?

**Comment by kaala** [comment]
Thank you, render result looks good.
