### ISSUE TITLE
Docker images as non root

### ISSUE THREAD

**Issue by lind** [yuzutech/kroki#612]
First thanks for Kroki @Mogztter! We're using Kroki from GitLab and have an installation of the images on OpenShift.

I was trying to change the [log configuration](https://github.com/yuzutech/kroki/blob/master/server/src/main/resources/logback.xml) mounting my own logback.xml file onto [/etc](https://github.com/yuzutech/kroki/blob/master/server/ops/docker/jdk11-alpine/Dockerfile#L33) but OpenShift wasn't happy. Probably because OpenShift don't "like" to run images as root.
[`* Don't run as root`](https://hub.docker.com/r/openshift/origin-custom-docker-builder/)
and therefore starts the Kroki image as another user. From the Kroki server console in OpenShift:

```
~ $ whoami
1002260000
~ $ ls -al /etc/logback.xml
-rw-rw-r--    1 root     root           487 Jul  5  2020 /etc/logback.xml
``` 
And probably that's why I wasn't allowed to mount a new logback.xml to the `root` owned file.
I don't think the Kroki server image (or the other images like [excalidraw](https://github.com/yuzutech/kroki/blob/master/excalidraw/Dockerfile) and others) has to be run as `root`. The rendering works on OpenShift for user `1002260000` at least...

The proposal is to change the [Dockerfile](https://github.com/yuzutech/kroki/blob/master/server/ops/docker/jdk11-alpine/Dockerfile) and introduce a kroki (?) [USER](https://docs.docker.com/engine/reference/builder/#user) and WORKDIR...

What do you think?

Proposal: https://github.com/yuzutech/kroki/pull/613

https://blog.karmacomputing.co.uk/building-non-root-docker-images-openshift/

**Comment by Mogztter** [comment]
Hey @lind, thanks for your kind words 🤗 

That's a good idea and it seems that most Docker images are using this best practice so 👍 

> The proposal is to change the Dockerfile and introduce a kroki (?) USER and WORKDIR...

I think we should apply this rule on all our Docker images for consistency. I'm fine with `kroki:kroki` (as `user:group`).

For reference, here's how redis does it:

```dockerfile
# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN addgroup -S -g 1000 redis && adduser -S -G redis -u 999 redis
# alpine already has a gid 999, so we'll use the next id
```

https://github.com/docker-library/redis/blob/231905d0841f52ee4f3a5b8b42d62cd6d14a1a93/6.2/alpine/Dockerfile#L4

We should probably move the `logback.xml` config to `/etc/kroki/logback.xml` and add `kroki:kroki` as a owner of `/etc/kroki`.

What do you think? Do you want to send a pull request to update the Docker images?

----

As a follow-up task, we might consider to adopt a more standard layout:
- Move `kroki-server.jar` to `/usr/local/kroki/kroki-server.jar`?
- Move binaries (`svgbob`, `erd`, `vega`, `wavedrom`...) to `/usr/bin`?

Since the Docker image only contains Kroki we could also put everything in a workdir (for instance, `/home/kroki` or `/usr/local/kroki`) but I don't really like this idea.

Thoughts?

**Comment by lind** [comment]
Sure `/usr/local/kroki` and `/etc/kroki/` might be better than `/home/kroki`. I have no strong opinion on that. 

Added user and group inspired from this [Docker file](https://github.com/better/baseimage/blob/db703e9337f6f63be40030c032cd7f10ed61ed5b/Dockerfile.alpine) and [this  comments](https://github.com/better/baseimage/pull/15/files). Not sure about the [-S (system user) option](https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user).

PR here: https://github.com/yuzutech/kroki/pull/613 (not covering the other Docker images yet)
The right direction @Mogztter ?

Move the other binaries to `/usr/bin`? Might be a good idea but I don't know pros and cons of doing that. Now the binaries are located under `/node/bin/`, `/haskell/bin/` etc. Is that a plan og just coincidence?

**Comment by lind** [comment]
Since the binaries now are owned by `root` but can be executed by another user it might be a good plan to collect all binaries under `/usr/bin`.
