### ISSUE TITLE
Create a Kroki plugin for Obsidian text editor

### ISSUE THREAD

**Issue by ggrossetie** [yuzutech/kroki#768]
[Obsidian](https://obsidian.md/) is an extensible text editor and provides an extension API for third-party plugins: https://help.obsidian.md/Advanced+topics/Third-party+plugins.

Would be nice to integrate Kroki into this text editor.

**Comment by gregzuro** [comment]
Bit of a hack, but: https://github.com/gregzuro/obsidian-kroki works...

**Comment by Mogztter** [comment]
ooh exciting! 🎉 
I will give it a try later this week 😃

**Comment by Mogztter** [comment]
@gregzuro Seems to be working fine. Is it possible to use SVG instead of PNG? It might be neat to have an option on Kroki to generate "dark mode" compatible diagrams.

Using light theme it looks great:

![image](https://user-images.githubusercontent.com/333276/124358603-569b9380-dc21-11eb-8bdc-bcfcebbde41b.png)


But not so great with dark theme:

![image](https://user-images.githubusercontent.com/333276/124358578-3ff53c80-dc21-11eb-8f38-badc764571d8.png)

Anyway, good work 👍🏻

**Comment by gregzuro** [comment]
> @gregzuro Seems to be working fine. Is it possible to use SVG instead of PNG? It might be neat to have an option on Kroki to generate "dark mode" compatible diagrams.

I *think* that I am using svg ( https://github.com/gregzuro/obsidian-kroki/blob/master/main.ts#L53 ) ?

I ran into the light/dark issue as well, though.  Need to look into it.

**Comment by Fashaun** [comment]
Sorry for that, what's the syntax of this plugin ? use code block with kroki string?
```kroki
```

**Comment by ggrossetie** [comment]
Closing, take a look at: https://github.com/gregzuro/obsidian-kroki
